name: philmoney
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter


 
  cupertino_icons: ^1.0.2
  get: ^4.6.5
  google_fonts: ^4.0.1
  firebase_core: ^2.9.0
  firebase_auth: ^4.2.1
  cloud_firestore: ^4.2.0
  firebase_storage: ^11.0.8

  flutter_easyloading: ^3.0.3
  
  barcode_widget: ^2.0.3

 # progress_timeline: ^0.0.5

  shimmer: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

 
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/images/
    - assets/icons/
    - assets/icons/banks/
  #   - images/a_dot_ham.jpeg

  fonts:
    - family: Avenir
      fonts:
        - asset: assets/fonts/Avenir-Book.ttf
          weight: 400 # normal
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/fonts/Montserrat-SemiBold.ttf
          weight: 600
    - family: Iconfont
      fonts:
        - asset: assets/fonts/iconfont.ttf
    - family: AppIcons
      fonts:
        - asset: assets/fonts/AppIcons.ttf