// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD5ToRf5vvVh9EU_-P2TCDXANpKogHnThA',
    appId: '1:620824275968:web:60acd7d26aacbfba1f7ce5',
    messagingSenderId: '620824275968',
    projectId: 'philmoney-db',
    authDomain: 'philmoney-db.firebaseapp.com',
    storageBucket: 'philmoney-db.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDYi2v-AWsurSLhNt7x_5SJdEDREEVbwts',
    appId: '1:620824275968:android:6172fcff0f2a03591f7ce5',
    messagingSenderId: '620824275968',
    projectId: 'philmoney-db',
    storageBucket: 'philmoney-db.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBR58Ole6O9JlUC4P-viXKAyQ9pk0O0_2U',
    appId: '1:620824275968:ios:e45bc1c9f4eadcd41f7ce5',
    messagingSenderId: '620824275968',
    projectId: 'philmoney-db',
    storageBucket: 'philmoney-db.appspot.com',
    iosClientId: '620824275968-8gusfmnloa2rhtsdo7mt4u19vb2ma0u9.apps.googleusercontent.com',
    iosBundleId: 'com.example.philmoney',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBR58Ole6O9JlUC4P-viXKAyQ9pk0O0_2U',
    appId: '1:620824275968:ios:e45bc1c9f4eadcd41f7ce5',
    messagingSenderId: '620824275968',
    projectId: 'philmoney-db',
    storageBucket: 'philmoney-db.appspot.com',
    iosClientId: '620824275968-8gusfmnloa2rhtsdo7mt4u19vb2ma0u9.apps.googleusercontent.com',
    iosBundleId: 'com.example.philmoney',
  );
}
